language: generic
sudo: false

cache:
  directories:
    - $HOME/.stack

matrix:
  fast_finish: true
  include:
    - env: BUILD=stack STACK_YAML=stack.yaml
      compiler: ": #stack"
      addons: {apt: {packages: [libx11-dev,libxtst-dev,libxrandr-dev,libgmp-dev], sources: [hvr-ghc]}}

# Note: the distinction between `before_install` and `install` is not important.
# - in before_install we install build tools
# - in install we install (haskell) dependencies

before_install:
  - unset CC
  - case "$BUILD" in
      stack)
        export PATH=$HOME/.local/bin:$PATH;;
    esac
  - mkdir -p $HOME/.local/bin
  - curl -sL https://www.stackage.org/stack/linux-x86_64 |
      tar xz --wildcards --strip-components=1 -C $HOME/.local/bin '*/stack'

install:
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - case "$BUILD" in
      stack)
        stack --no-terminal test --only-dependencies --install-ghc;;
    esac

script:
  - set -e; case "$BUILD" in
      stack)
        stack --no-terminal test --haddock --no-haddock-deps --ghc-options="-Werror";;
    esac
